# Generated by Django 5.1.15 on 2026-10-06 07:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_teachingassignment_section_academic_year_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Homework title or topic heading.', max_length=200)),
                ('description', models.TextField(help_text='Detailed instructions, reading passages, or questions.')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='Date when homework was assigned/published.')),
                ('due_date', models.DateField(blank=True, help_text='Submission due date for students.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='PUBLISHED', help_text='Lifecycle status: DRAFT, PUBLISHED, or CLOSED.', max_length=16)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this homework assignment.', on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='academics.academicyear')),
                ('faculty', models.ForeignKey(help_text='Faculty member who created and assigned this homework.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_homework', to='accounts.faculty')),
                ('school_class', models.ForeignKey(help_text='Class for this homework.', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='academics.schoolclass')),
                ('section', models.ForeignKey(help_text='Section for which this homework is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='academics.section')),
                ('subject', models.ForeignKey(help_text='Subject to which this homework belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'db_table': 'homework',
                'ordering': ['-assigned_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_hw_status'), models.Index(fields=['section', 'status'], name='idx_hw_sec_status'), models.Index(fields=['faculty', 'status'], name='idx_hw_fac_status'), models.Index(fields=['due_date'], name='idx_hw_due_date')],
            },
        ),
    ]
