# Generated by Django 5.1.15 on 2026-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed instructions, reading passages, or questions.'),
        ),
    ]
