# Generated by Django 5.1.15 on 2026-09-29 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('session_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE')], max_length=16)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_attendances', to='accounts.faculty')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.enrollment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'session_period'],
                'indexes': [models.Index(fields=['enrollment', 'date'], name='attendance__enrollm_224ee2_idx'), models.Index(fields=['date', 'status'], name='attendance__date_0c5e7f_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date', 'session_period'), name='unique_attendance_per_session', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('status__in', ['PRESENT', 'ABSENT', 'ON_DUTY', 'LEAVE'])), name='check_valid_attendance_status')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Medical', 'Medical Leave'), ('Casual', 'Casual Leave'), ('Duty', 'Duty Leave'), ('Other', 'Other')], default='Casual', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_applications', to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='students.student')),
            ],
            options={
                'db_table': 'attendance_leave_applications',
                'ordering': ['-applied_on'],
                'indexes': [models.Index(fields=['student', 'status'], name='attendance__student_305865_idx'), models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_b72bcb_idx')],
            },
        ),
    ]
