# Generated by Django 5.1.15 on 2026-09-28 13:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Principal", "Principal"),
                            ("Faculty", "Faculty"),
                            ("Student", "Student"),
                            ("Parent", "Parent"),
                        ],
                        help_text="ERP system role. One of: Admin, Principal, Faculty, Student, Parent.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of role responsibilities.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID v4 primary key — database identity, separate from business identifiers.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number.",
                        max_length=32,
                    ),
                ),
                (
                    "avatar_url",
                    models.TextField(
                        blank=True, default="", help_text="Profile avatar image URL."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Auto-updated timestamp on every save."
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="ERP role assignment. RESTRICT: prevents deleting a role while users are assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Legal Guardian", "Legal Guardian"),
                        ],
                        help_text="Guardian's relationship to the student.",
                        max_length=32,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="CASCADE: Deleting the user record removes this parent profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "db_table": "parents",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        help_text="Unique institutional staff code (e.g. FAC001). Immutable after assignment.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Academic department (e.g. Mathematics, Physics, Computer Science).",
                        max_length=100,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Official designation (e.g. PGT Mathematics, TGT Science, HOD Physics).",
                        max_length=100,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Highest academic qualification (e.g. M.Sc, B.Ed, M.Phil).",
                        max_length=255,
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Subject specialization details.",
                    ),
                ),
                (
                    "office_room",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Faculty office or staff room location.",
                        max_length=64,
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        help_text="Date of institutional appointment/joining."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive faculty are retained for historical audit but not scheduled.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="CASCADE: Deleting the user record removes this faculty profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculty",
                "db_table": "faculty",
                "ordering": ["department", "user__last_name"],
                "indexes": [
                    models.Index(fields=["department"], name="idx_faculty_department"),
                    models.Index(fields=["is_active"], name="idx_faculty_is_active"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="idx_users_role"),
        ),
    ]
