# Generated by Django 5.1.15 on 2026-09-28 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable class name (e.g. 'Grade 11 - Computer Science', 'Grade 9').",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short class code (e.g. 'G11-CS', 'G10-GEN', 'G9').",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["academic_year", "code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section label (e.g. 'A', 'A1', 'B2', 'C3').",
                        max_length=32,
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Assigned classroom or room number.",
                        max_length=64,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=35,
                        help_text="Maximum student enrollment capacity for this section.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "sections",
                "ordering": ["school_class", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full subject name (e.g. 'Mathematics', 'Computer Science', 'Physics').",
                        max_length=150,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique subject code (e.g. 'MATH11', 'CS12', 'PHY11B').",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Academic department owning this subject.",
                        max_length=100,
                    ),
                ),
                (
                    "weekly_periods",
                    models.IntegerField(
                        default=6,
                        help_text="Number of instructional periods per week. Replaces 'credits' (purged per ADR 008 Indian school reconciliation).",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive subjects are retained for historical marks but not scheduled.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Academic year label (e.g. '2025-2026', '2026-2027').",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="First day of the academic year."),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Last day of the academic year."),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the currently active academic year. Only one should be True at a time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_years",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_current"], name="idx_academic_years_is_current"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrolled_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date on which the enrollment was registered.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Enrolled", "Enrolled"),
                            ("Promoted", "Promoted"),
                            ("Transferred", "Transferred"),
                            ("Graduated", "Graduated"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        default="Enrolled",
                        help_text="Current enrollment lifecycle status.",
                        max_length=32,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="CASCADE: Deleting an academic year removes all its enrollment records.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-academic_year__start_date", "student__student_id"],
            },
        ),
    ]
