# Generated by Django 5.1.15 on 2026-09-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="CASCADE: Deleting a student removes all their enrollment records.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="academic_year",
            field=models.ForeignKey(
                help_text="PROTECT: Cannot delete an academic year that has class definitions.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="SET_NULL: Removing a faculty record marks this section as unassigned rather than deleting the section itself.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sections",
                to="accounts.faculty",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="school_class",
            field=models.ForeignKey(
                help_text="CASCADE: Deleting a class cascades to and removes all its sections.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academics.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                help_text="CASCADE: Deleting a section removes its associated enrollment records.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.section",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["department"], name="idx_subjects_department"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["is_active"], name="idx_subjects_is_active"),
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("academic_year", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("school_class", "name")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["section", "academic_year"], name="idx_enrollments_section_year"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="idx_enrollments_status"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "academic_year")},
        ),
    ]
