# Generated by Django 5.1.15 on 2026-10-06 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Active status of this teaching assignment.')),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'db_table': 'teaching_assignments',
                'ordering': ['academic_year', 'school_class', 'section', 'subject'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Direct link to academic year for cardinality constraints and efficient scoping.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicyear'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_year__isnull', False), ('class_teacher__isnull', False)), fields=('academic_year', 'class_teacher'), name='unique_faculty_class_teacher_per_academic_year'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for which this teaching assignment is active.', on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='faculty',
            field=models.ForeignKey(help_text='The faculty member authorized to teach this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='school_class',
            field=models.ForeignKey(help_text='Class of the assigned section.', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='section',
            field=models.ForeignKey(help_text='Section where the subject is taught.', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(help_text='Subject being taught.', on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['faculty', 'is_active'], name='idx_teach_fac_active'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['section', 'subject'], name='idx_teach_sec_sub'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'section', 'subject', 'academic_year'), name='unique_faculty_section_subject_per_year'),
        ),
    ]
