# Generated by Django 5.1.15 on 2026-09-29 08:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marks_exam_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('remarks', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.enrollment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_marks', to='accounts.faculty')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='marks.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.subject')),
            ],
            options={
                'db_table': 'marks_records',
                'ordering': ['enrollment', 'subject', 'exam_type'],
                'indexes': [models.Index(fields=['enrollment', 'subject'], name='marks_recor_enrollm_40433c_idx'), models.Index(fields=['exam_type', 'subject'], name='marks_recor_exam_ty_61af91_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'subject', 'exam_type'), name='unique_student_subject_exam_mark'), models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0), ('marks_obtained__lte', models.F('max_marks'))), name='check_marks_obtained_range')],
            },
        ),
    ]
