# Generated by Django 5.1.15 on 2026-09-28 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Permanent immutable business identifier. Format: STU<4-digit-year><5-digit-sequence> (e.g. STU202600001). IMMUTABLE after creation. Cannot be modified via any update operation.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        help_text="Unique institutional admission number (e.g. ADM20240091).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Class roll number (e.g. 11-A2-04). May change on section transfer.",
                        max_length=64,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        help_text="Emergency contact phone number.", max_length=32
                    ),
                ),
                ("address", models.TextField(help_text="Home address.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Enrolled", "Enrolled"),
                            ("Promoted", "Promoted"),
                            ("Transferred", "Transferred"),
                            ("Graduated", "Graduated"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        default="Enrolled",
                        help_text="Current enrollment lifecycle status.",
                        max_length=32,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="PROTECT: Cannot delete a parent record while students are linked. NULL permitted — a student may not yet have a linked parent account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounts.parent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="CASCADE: Deleting the user record removes this student profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "ordering": ["student_id"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_students_status"),
                    models.Index(fields=["parent"], name="idx_students_parent"),
                ],
            },
        ),
    ]
